services:
  - type: web
    name: weather-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
    disk:
      name: models
      mountPath: /opt/render/project/src/models
      sizeGB: 1
  